@host = app-api-platform-security.azurewebsites.net
#@host = localhost:5001

### Retrieve all repairs
GET http://{{host}}/api/Repairs

### Retrieve specific repair
GET http://{{host}}/api/Repairs/1

### Create repair
POST http://{{host}}/api/Repairs
Content-Type: application/json

{
    "asset": {
        "assetType": "Traffic Light",
        "location": "Corner of Kings Avenue and Rose street"
    },
    "requester": {
        "name": "Eldert Grootenboer",
        "phoneNumber": "0612345678",
        "email": "eldert@eldert.net"
    }
}

### Update repair
PUT http://{{host}}/api/Repairs/500
Content-Type: application/json

{
    "id": 500,
    "Status": "Finished"
}

### Delete repair
DELETE http://{{host}}/api/Repairs/4