@host = http://app-api-platform-security-2.azurewebsites.net
#@host = https://localhost:5001

### Retrieve all repairs
GET {{host}}/api/Repairs

### Retrieve specific repair
GET {{host}}/api/Repairs/1

### Create repair
POST {{host}}/api/Repairs
Content-Type: application/json

{
    "asset": {
        "assetType": "Traffic Light",
        "location": "Corner of Kings Avenue and Rose street"
    },
    "requester": {
        "name": "Eldert Grootenboer",
        "phoneNumber": "0612345678",
        "email": "eldert@eldert.net"
    }
}

### Update repair
PUT {{host}}/api/Repairs/4
Content-Type: application/json

{
    "id": 4,
    "Status": "Finished"
}

### Delete repair
DELETE {{host}}/api/Repairs/4