@host = apim-api-platform-security-ox7dl67n2oae2.azure-api.net


# 1 - Basic Authentication
### Missing authentication
GET http://{{host}}/demo1/repairs
Ocp-Apim-Subscription-Key: {{apiManagementSubscriptionKey}}

### Basic authentication
GET http://{{host}}/demo1/Repairs
Authorization: Basic {{basicAuthenticationPassword}}
Ocp-Apim-Subscription-Key: {{apiManagementSubscriptionKey}}

# 2 - OAuth
### OAuth2 authentication
# @name auth
POST https://login.microsoftonline.com/{{tenantId}}/oauth2/v2.0/token HTTP/1.1
Content-type: application/x-www-form-urlencoded	

grant_type=client_credentials
&client_id={{clientId}}
&client_secret={{clientSecret}}
&scope={{scope}}

### Get repairs using OAuth2
GET http://{{host}}/demo2/repairs
Authorization: Bearer {{auth.response.body.access_token}}
Ocp-Apim-Subscription-Key: {{apiManagementSubscriptionKey}}