@host = apim-api-platform-security.azure-api.net

### Non-throttled
GET https://{{host}}/demo/repairs
Ocp-Apim-Subscription-Key: {{apiManagementSubscriptionKey}}

# 6 - Throttling
### OAuth2 authentication
# @name auth
POST https://login.microsoftonline.com/{{tenantId}}/oauth2/v2.0/token HTTP/1.1
Content-type: application/x-www-form-urlencoded	

grant_type=client_credentials
&client_id={{clientId}}
&client_secret={{clientSecret}}
&scope={{scope}}

### Get repairs using OAuth2 with throttling
GET https://{{host}}/demo6/repairs
Authorization: Bearer {{auth.response.body.access_token}}
Ocp-Apim-Subscription-Key: {{apiManagementSubscriptionKey}}